### ISSUE TITLE
Add NDI PTZ Control 

### ISSUE THREAD

**Issue by AidanNelson** [AutoPTZ/autoptz#33]
**Is your feature request related to a problem? Please describe.**
Hi there!

This is exciting program.  Thanks for putting it together.  I would love to use it with an NDI camera using NDI PTZ Control.  

Two questions:
- Are you planning to add an open-source license?  
- Do you plan to add NDI PTZ Control?  Or, would you be up for a PR related to this? 

**Describe the solution you'd like**
NDI Cameras can be controlled using NDI PTZ Control (rather than VISCA or other control schemes)

**Comment by TCVinNYC** [comment]
Hey @AidanNelson !

Thank you so much for the support and suggestions.

1. I am planning to add open-source license I just haven't gone around to doing it and figuring out which one to use haha.
2. I recently figured out the NDI PTZ Control which is so much better than that VISCA Network since it would be automatically assigned. If you'd like to create a PR for it that'd be awesome, otherwise expect a PR for it this weekend or so.

We also have a discord server if you'd like to join and chat more about it!
https://discord.gg/vYUpPf9FKs

**Comment by AidanNelson** [comment]
Great!

Some cameras have limited VISCA support, so NDI would also help expand the range of potential uses for this project.

I understand choosing a license can be difficult.  This site has been helpful for me in the past: https://choosealicense.com/

I'll look through the codebase to see if I can contribute something next week.

**Comment by TCVinNYC** [comment]
I just recreated a PR for the NDI control. I'll be able to truly test it's functionalities tomorrow.

Thank you for the license link, I went with GNU GPLv3. 

I'd love to hear and see any suggestions and PR's to make the project as best as possible.

**Comment by AidanNelson** [comment]
Very cool.  I'll try it out on Monday.  And I'm glad to hear about the license.

**Comment by TCVinNYC** [comment]
So in my PR testing it does work decently well.

But even on high end systems we run into Facial Recognition multithreading issues due to Python's GIL. I could use multiprocessing, but it takes much longer to first queue and execute.

We can either move to something like C++ entirely or set some special timing for how often facial recognition should decide to run.

Unless you have other ideas?

**Comment by AidanNelson** [comment]
Hmm... I guess that depends on the ultimate goal of this library.  How are you imagining using this tool?  

There is value in a simple implementation -- even if not fully optimized -- if it provides a clear demonstration of these techniques for other developers. On the other hand,  if you'd like this to use this tool in production (i.e. for live-streaming or whatever your use case is), then I would start with the quickest-to-implement optimizations before move towards the more drastic (i.e. switching to C++).  That is just my $0.02.  

Excited to try it! 🎥😀

**Comment by TCVinNYC** [comment]
Mm I see. I do like it being simple and easy for other developers to look at for reference.

Overall I think the end goal is to allow people to use it i a production setting- essentially a free replacement to Panasonic's AW-SF program.

I wouldn't really know how to best optimize it. I think it would be a great idea to use Deep Learning models for body tracking instead of solely relying on facial recognition for an outline.
Though everything I've tried seems too slow for real-time use or not as accurate.

Also I'm excited to hear on what you think of the PR!
